version: 2

builds:
  - main: ./cmd/mmd-cli
    binary: mmd-cli
    ldflags:
      - -s -w -X github.com/coolamit/mermaid-cli/internal/cli.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "mmd-cli_{{.Version}}_{{ if eq .Os \"darwin\" }}macos{{ else }}{{ .Os }}{{ end }}_{{ if eq .Arch \"amd64\" }}x64{{ else }}{{ .Arch }}{{ end }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: coolamit
    name: mermaid-cli
